"""author names as list for versions

Revision ID: 98a661750206
Revises: c4edf20606da
Create Date: 2026-03-25 12:57:06.655317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98a661750206'
down_revision: Union[str, Sequence[str], None] = 'c4edf20606da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_versions', 'author',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='author::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_versions', 'author',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='author::jsonb')
    # ### end Alembic commands ###
