"""create tables

Revision ID: e2b26029c87d
Revises: 
Create Date: 2026-03-25 12:22:57.292433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2b26029c87d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('log_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.create_table('async_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_job_id'), 'async_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_async_jobs_tenant_id'), 'async_jobs', ['tenant_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('work_identifier', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('first_publish_year', sa.Integer(), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_books_tenant_author', 'books', ['tenant_id', 'author'], unique=False)
    op.create_index(op.f('ix_books_tenant_id'), 'books', ['tenant_id'], unique=False)
    op.create_index('ix_books_tenant_title', 'books', ['tenant_id', 'title'], unique=False)
    op.create_index('ix_books_tenant_year', 'books', ['tenant_id', 'first_publish_year'], unique=False)
    op.create_index(op.f('ix_books_work_identifier'), 'books', ['work_identifier'], unique=False)
    op.create_index('uq_books_tenant_work_identifier', 'books', ['tenant_id', 'work_identifier'], unique=True)
    op.create_table('book_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('first_publish_year', sa.Integer(), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_versions_book_id'), 'book_versions', ['book_id'], unique=False)
    op.create_index('ix_book_versions_book_version_at', 'book_versions', ['book_id', 'version_at'], unique=False)
    op.create_index('uq_book_versions_book_version_number', 'book_versions', ['book_id', 'version_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_book_versions_book_version_number', table_name='book_versions')
    op.drop_index('ix_book_versions_book_version_at', table_name='book_versions')
    op.drop_index(op.f('ix_book_versions_book_id'), table_name='book_versions')
    op.drop_table('book_versions')
    op.drop_index('uq_books_tenant_work_identifier', table_name='books')
    op.drop_index(op.f('ix_books_work_identifier'), table_name='books')
    op.drop_index('ix_books_tenant_year', table_name='books')
    op.drop_index('ix_books_tenant_title', table_name='books')
    op.drop_index(op.f('ix_books_tenant_id'), table_name='books')
    op.drop_index('ix_books_tenant_author', table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_async_jobs_tenant_id'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_job_id'), table_name='async_jobs')
    op.drop_table('async_jobs')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
